AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Morpho Liquidation Bot deployed using AWS Lambda function


Globals:
  Function:
    Timeout: 800

Parameters:

  AlchemyKey:
    Type: "AWS::SSM::Parameter::Value<String>"
    Description: The Alchemy key to use for the RPC
    Default: /stage/morpho/main/prod/liquidation/ALCHEMY_KEY

  PrivateKeySecretId:
    Type: String
    Description: The Private key Secret manager name
    Default: PrivateKeyMainnet-zAzXaF

  ScheduledRate:
    Type: String
    Description: The Rate for a liquidation check
    Default: 15 minutes

  BatchSize:
    Type: String
    Description: The Batch size for a liquidation check
    Default: 200

  LiquidatorCompoundContractAddress:
    Type: String
    Description: The Liquidator Contract Address
    Default: "0xFB83F4b543b8946c08F352c90123BF3Fd679178c"

  LiquidatorAaveContractAddress:
    Type: String
    Description: The Liquidator Contract Address
    Default: "0xeAFa4445D5734Cb9356FB7f842C5Ba46a07153CB"


Resources:
  LiquidationBotCompound:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Architectures:
        - x86_64
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub
              - "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretId}"
              - { SecretId: !Ref PrivateKeySecretId }
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - "rate(${ScheduledRate})"
              - { ScheduledRate: !Ref ScheduledRate }
            Enabled: True
      Environment:
        Variables:
          SECRET_ID: !Ref PrivateKeySecretId
          ALCHEMY_KEY: !Ref AlchemyKey
          LIQUIDATOR_ADDRESS: !Ref LiquidatorCompoundContractAddress
          PROFITABLE_THRESHOLD: 50 # in USD
          SECRET_NAME: PrivateKeyMainnet
          BATCH_SIZE: !Ref BatchSize
          IS_COMPOUND: true
    Metadata:
      DockerTag: nodejs16.x-v1
      DockerContext: .
      Dockerfile: bot.Dockerfile
  LiquidationBotAave:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Architectures:
        - x86_64
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub
              - "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretId}"
              - { SecretId: !Ref PrivateKeySecretId }
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - "rate(${ScheduledRate})"
              - { ScheduledRate: !Ref ScheduledRate }
            Enabled: True
      Environment:
        Variables:
          SECRET_ID: !Ref PrivateKeySecretId
          ALCHEMY_KEY: !Ref AlchemyKey
          PROFITABLE_THRESHOLD: 50 # is USD
          LIQUIDATOR_ADDRESS: !Ref LiquidatorAaveContractAddress
          SECRET_NAME: PrivateKeyMainnet
          BATCH_SIZE: !Ref BatchSize
    Metadata:
      DockerTag: nodejs16.x-v1
      DockerContext: .
      Dockerfile: bot.Dockerfile

Outputs:
  LiquidationBotCompoundFunction:
    Description: "Liquidation Lambda Function ARN for Morpho Compound"
    Value: !GetAtt LiquidationBotCompound.Arn
  LiquidationBotAaveFunction:
    Description: "Liquidation Lambda Function ARN for Morpho Aave"
    Value: !GetAtt LiquidationBotAave.Arn